spring:
  application:
    name: dubbo-springboot-provider
dubbo:
  protocol:
    name: dubbo
    port: -1

  registry:
    address: nacos://127.0.0.1:8848
    register-mode: instance # 注册模式：instance interface all
